### ISSUE TITLE
GO Cellular Component 2017 error 

### ISSUE THREAD

**Issue by harrydgnt** [wjawaid/enrichR#1]
Hello 

I am trying to use enrichR to get GO analysis info in R. 

For other processes, it works fine but when I try to use enrichr for "GO_Cellular_Component_2017b" database, I get this error: 

`Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 2 elements`

This works for fine with other GO databases such as "GO_Molecular_Function_2017b" 

The input data is list of genes.

**Comment by wjawaid** [comment]
I think this is now resolved thanks to @shka .
