### ISSUE TITLE
Unable to connect with EnrichR

### ISSUE THREAD

**Issue by gowthamee** [wjawaid/enrichR#10]

**Comment by gowthamee** [comment]
`listEnrichrDbs()`

results in data frame with 0 columns and 0 rows

I am checking if this is a problem with the EnrichR website, but meanwhile I would like to know if anyone has faced this issue in the last few days. If so, any input is appreciated.

**Comment by wjawaid** [comment]
This appears to be a problem with the website at the moment. If you test a handful of genes on the website - nothing happens. The package should work when the website comes back online.
