### ISSUE TITLE
Error after updating enrichR package 

### ISSUE THREAD

**Issue by mmkhan19** [wjawaid/enrichR#11]
Hi Wajid,
After updating the enrichR package we got an unexpected error:

> listEnrichrDbs()
Error in fromJSON(dbs) : unexpected character '<'

Have sent you an email with more details.

Thanks,
Mohammed

**Comment by bblum9** [comment]
We're seeing this as well. Is this package still being supported?

**Comment by ruoyijiang** [comment]
Looks like you guys moved to ```https://amp.pharm.mssm.edu/Enrichr3/datasetStatistics``` but the functions are still pulling from  ```https://amp.pharm.mssm.edu/Enrichr/datasetStatistics``` in the code?

Line 18 in https://github.com/wjawaid/enrichR/blob/master/R/functions.R
```
dbs <- GET(url="http://amp.pharm.mssm.edu/Enrichr/datasetStatistics")$content
```

**Comment by ytakemon** [comment]
I'm encountering the same issue as well. Hoping that this package is still supported.

**Comment by mmkhan19** [comment]
enrichR is now up and running hence closing the issue.
