### ISSUE TITLE
enrichr function works, but does not download the "overlap" column in its entirety

### ISSUE THREAD

**Issue by gowthamee** [wjawaid/enrichR#17]

**Comment by gowthamee** [comment]
`enrichr_topTable <- enrichr(enrich_input, database_names)`
 `enrichr_topTable[[1]]`
 The output for the above code looks like the following with the denominator of the overlap column missing
![image](https://user-images.githubusercontent.com/8107460/61322183-1e53de00-a7db-11e9-8543-6ff9bcb20b65.png)

Any insight is most appreciated. Thanks !!!

**Comment by wjawaid** [comment]
It appears to be working now. Have updated to version2

  Overlap      P.value
1    3/63 5.916837e-07
2    3/88 1.630456e-06
3    3/90 1.745124e-06
4   4/464 4.134121e-06
Thanks for the feedback
