### ISSUE TITLE
enrichR function works now, but Old.P value and Ol.dAdj P value are always 0.

### ISSUE THREAD

**Issue by Danya-Gordin** [wjawaid/enrichR#18]
Everytime I run enrichR on various data sets, the Old.P and Old.AdjP values are always 0.
Furthermore, the results from my analysis are very different when compared to a csv I saved of enrichR two weeks ago before the update (list of input genes is obviously exactly the same).
New results after enrichR update:
<img width="1335" alt="Screen Shot 2019-07-16 at 7 26 05 PM" src="https://user-images.githubusercontent.com/47399231/61336731-718c5780-a800-11e9-9b1b-f8071973e959.png">

Two week old results:
<img width="1347" alt="Screen Shot 2019-07-16 at 7 33 36 PM" src="https://user-images.githubusercontent.com/47399231/61336803-c203b500-a800-11e9-8bbc-581ef379c87a.png">

**Comment by wjawaid** [comment]
Hi
It appears the website (http://amp.pharm.mssm.edu/Enrichr/) no longer returns the result. It is giving 0 on old p-values. This was for compatibility with their previous method - it may now be deprecated so stick to the new method of p-value calculation.
Thanks
