### ISSUE TITLE
base address is not loaded on startup

### ISSUE THREAD

**Issue by lachmann12** [wjawaid/enrichR#20]
Setting options in the source file does not seem to work. The URL probably has to be set in the function.

https://github.com/wjawaid/enrichR/blob/feac0d979a1bd0cd09cda3ec9fe9848b87b946c6/R/functions.R#L6

6f47dc8d578fa0b56c7e1e616041e42be0ab6e31

**Comment by wjawaid** [comment]
Thanks. I've fixed it on v2.1
