### ISSUE TITLE
EnrichR website not responding

### ISSUE THREAD

**Issue by Danya-Gordin** [wjawaid/enrichR#22]
When I attempt to run:
```r
listEnrichrDbs()
```
I get the error:
"EnrichR website not responding"

**Comment by mukund-asimov** [comment]
Same!

**Comment by hirscheylab** [comment]
Solution here: https://stackoverflow.com/questions/57570038/how-to-solve-enrichr-website-not-responding/57701786#57701786

**Comment by wjawaid** [comment]
I have uploaded the latest (v2.1) to CRAN - awaiting approval.
