### ISSUE TITLE
Enrichr website not repsonding

### ISSUE THREAD

**Issue by kunstner** [wjawaid/enrichR#23]
Hi, 

I'm using enrichR version 2.1 (R 3.6.1). Unfortunately, I get an error message when I try to use the package:

dbs <- enrichR::listEnrichrDbs()
EnrichR website not responding

Any idea how to fix this?

Best,
 Axel

**Comment by hirscheylab** [comment]
See this post: https://stackoverflow.com/questions/57570038/how-to-solve-enrichr-website-not-responding/57701786#57701786

**Comment by kunstner** [comment]
@hirscheylab actually, I'm using this version. I even uninstalled enrichR and used

devtools::install_github("wjawaid/enrichR")

to reinstall it. Same result as described above.

**Comment by hirscheylab** [comment]
Sorry; thought I'd try to help. 
FWIW: working for me. Just pinged it with `listEnrichrDbs()`

**Comment by kunstner** [comment]
Seems to be working for me again. Could not figure out what the problem was. Anyhow @hirscheylab thanks for your help!
