### ISSUE TITLE
No results when inputting genes with scores

### ISSUE THREAD

**Issue by chilampoon** [wjawaid/enrichR#24]
Hi, I am using EnrichR to analyze my DEGs gotten from limma. 
I extracted subsets of significant DEGs with their IDs and t-statistics that have been scaled, like the following example:

```
CHI3L1 1.0000000
ARPC1B 0.9605097
SH3D21 0.9303946
FCGBP 0.9165999
MFNG 0.8830144
C2 0.8153162
CTA-398F10.2 0.8459803
CTSD 0.7543101
GRN 0.7503898
CTSB 0.6984719
```
The command I used was `enrichr(gene.df, dbs)`.

However, the dataframes of enrichr results were all empty
![image](https://user-images.githubusercontent.com/43943114/81492693-93dded00-92cc-11ea-886e-87f25b8b5f9a.png)

So I am wondering how to fix it? Thanks!

I was using R 3.6.3 and enrichR 2.1.

**Comment by wjawaid** [comment]
Hi, Thanks for using the package. I have uploaded the genes directly to the website (http://amp.pharm.mssm.edu/Enrichr/enrich) using the weights and it provides no results.

I think there is currently an issue with the website itself rather than the package.
