### ISSUE TITLE
Throwing an error if EnrichR website is not responding

### ISSUE THREAD

**Issue by ktrns** [wjawaid/enrichR#25]
Hi! 

Thank you for your nice package! 

Would it make sense to throw an error, when the package is loaded but the website is not responding, rather than writing a message?

```
> library(enrichR)
Welcome to enrichR
Checking connection ... EnrichR website not responding
```

The error could be used to stop a script that is using the enrichR package. 

Thanks a lot in advance!
Katrin

**Comment by wjawaid** [comment]
Hi Katrin,

Thank you for using the package and for the excellent suggestion. I'll make the changes.

Wajid

**Comment by ktrns** [comment]
Hi there, 

Just wondering whether there was any update with regard to this issue? 

Many thanks in advance, 
Katrin

**Comment by wjawaid** [comment]
Hi. I had a look. 
The problem is if an error is thrown it will effect the loading of the package. One way to check in your own code is to check if <getOption("enrichR.live")> returns <FALSE> and throw an error in your own code.
