### ISSUE TITLE
Downstream tools

### ISSUE THREAD

**Issue by kasumaz** [wjawaid/enrichR#26]
Dear Authors, 
I used the EnrichR package. I am wondering, if there has been any attempt to turn the output data into plots with added on scripts like ggploting? I would be interested in such an add on script. I have multiple gene lists at times for different cell clusters to then to ideally show in some kind of plot all together. Could there be something done to make it streamlined? 
Thanks.

**Comment by wjawaid** [comment]
Hi,

Thanks for using the package and your comment. I've thought about it but the data may be used in a variety of ways. It is not clear from your comment exactly what plot you would like. Do you want plots similar to those provided by the website? Generating the required plots is not difficult either in base plot or ggplot but the variability in required plots makes it easier for the user to generate their own plot. If you can be specific for what you like, I can look into it again.

**Comment by kasumaz** [comment]
Hi, Thanks for replying. With the EnrichR package as is, its maybe difficult for a non export to turn the data from any gene list into ggplot plots, such as dotplots where you have the sample type/conditions (different gene lists) on one axis and then the pathway terms on another axis. In a dotplot, the combined scores (pvalue/z-score) could represent the size of the dot. If this could be done systematically for the different types of GO, Pathway, Transcription, etc features on the web version of Enrichr, this could be an important tool. Also giving the user aesthetic options for colours, etc. I can always help with this as I use Enrichr web version and make my own ggplots for whatever GO/pathway analysis.  
Best regards.
