### ISSUE TITLE
Can't reach EnrichR website

### ISSUE THREAD

**Issue by hwessels** [wjawaid/enrichR#29]
Hi, 

I have used EnrichR before. Currently, it may be unresponsive.
New data sets and previously run code does currently not execute with the following error message:

`EnrichR website not responding
 Error in do.call(what = cbind, args = pos.er) : 
  second argument must be a list `

I don't think it is code/R version related. 

I tried to install EnrichR again from GitHub using devtools as suggested here: https://stackoverflow.com/questions/57570038/how-to-solve-enrichr-website-not-responding
But that didn't help

could you please look into this?

**Comment by Liuy12** [comment]
I am having the same issue. Seems like the web server is down

**Comment by chris-mcginnis-ucsf** [comment]
same issue here...

**Comment by wjawaid** [comment]
It may have been a temporary problem with their webserver. Appears to be working now.

**Comment by hwessels** [comment]
Thank you for checking, but It does not seem to be resolved:
`EnrichR website not responding`

**Comment by wjawaid** [comment]
What happens when you load the package?
Do you get:
> Welcome to enrichR
> Checking connection ... Connection is Live!
?

**Comment by hwessels** [comment]
know I get the startup message and it runs. 
I hope the EnrichR server keeps being reachable

**Comment by hwessels** [comment]
know I get the startup message and it runs. 
I hope the EnrichR server keeps being reachable

**Comment by hwessels** [comment]
know I get the startup message and it runs. 
I hope the EnrichR server keeps being reachable

**Comment by hwessels** [comment]
Offline again

**Comment by pollicipes** [comment]
> It may have been a temporary problem with their webserver. Appears to be working now.

Hi wjawaid,

The server is still down. Do you know what can be causing it? The address now for the enrichR is different from the one before. Now is [(https://maayanlab.cloud/Enrichr/)] https://maayanlab.cloud/Enrichr/ Might it be related?
Hope you can help here! enrichR is such a good tool!

Thanks!
Best,
J
