### ISSUE TITLE
Empty enrichment results

### ISSUE THREAD

**Issue by markdane** [wjawaid/enrichR#32]
Hi,

I'm getting a list of data.frames with 0 rows when I run the vignette code.

> dbs <- c("GO_Molecular_Function_2015", "GO_Cellular_Component_2015", "GO_Biological_Process_2015")
> enriched <- enrichr(c("Runx1", "Gfi1", "Gfi1b", "Spi1", "Gata1", "Kdr"), dbs)
Uploading data to Enrichr... Done.
  Querying GO_Molecular_Function_2015... Done.
  Querying GO_Cellular_Component_2015... Done.
  Querying GO_Biological_Process_2015... Done.
Parsing results... Done.
> enriched[["GO_Biological_Process_2015"]]
[1] Term                 Overlap              P.value             
[4] Adjusted.P.value     Old.P.value          Old.Adjusted.P.value
[7] Odds.Ratio           Combined.Score       Genes               
<0 rows> (or 0-length row.names)

Can I get some guidance for this?

**Comment by paularstrpo** [comment]
Just want to piggy back on this issue to mention me and two other coworkers are having the same problem today.

**Comment by wjawaid** [comment]
Hi

Is the package loading up and saying it is live?
On my machine it appears to work giving the following output:

```
>library(enrichR)
Welcome to enrichR
Checking connection ... Connection is Live!
> dbs <- c("GO_Molecular_Function_2015", "GO_Cellular_Component_2015", "GO_Biological_Process_2015") 
> enriched <- enrichr(c("Runx1", "Gfi1", "Gfi1b", "Spi1", "Gata1", "Kdr"), dbs)
Uploading data to Enrichr... Done.
  Querying GO_Molecular_Function_2015... Done.
  Querying GO_Cellular_Component_2015... Done.
  Querying GO_Biological_Process_2015... Done.
Parsing results... Done.
> head(enriched[["GO_Biological_Process_2015"]])
                                                              Term Overlap
1                               embryonic hemopoiesis (GO:0035162)    3/24
2          regulation of myeloid cell differentiation (GO:0045637)   4/156
3           regulation of erythrocyte differentiation (GO:0045646)    3/36
4 positive regulation of myeloid cell differentiation (GO:0045639)    3/74
5                                         hemopoiesis (GO:0030097)    3/95
6       hematopoietic progenitor cell differentiation (GO:0002244)   3/106
       P.value Adjusted.P.value Old.P.value Old.Adjusted.P.value Odds.Ratio
1 3.028853e-08     0.0001572581           0                    0  416.66667
2 5.277328e-08     0.0001369994           0                    0   85.47009
3 1.067057e-07     0.0001846720           0                    0  277.77778
4 9.646700e-07     0.0012521417           0                    0  135.13514
5 2.054951e-06     0.0021338606           0                    0  105.26316
6 2.860606e-06     0.0024753773           0                    0   94.33962
  Combined.Score                  Genes
1       7213.540        KDR;GATA1;RUNX1
2       1432.245 GFI1B;SPI1;GATA1;RUNX1
3       4459.220       GFI1B;SPI1;GATA1
4       1871.822      GFI1B;GATA1;RUNX1
5       1378.448        KDR;GATA1;RUNX1
6       1204.196       SPI1;GATA1;RUNX1
```
Sometimes there can be issues with the webserver and it may have been down. To check if that's the case, try a quick manual check on the website with a handfull of genes (https://maayanlab.cloud/Enrichr/). It should also show up as a problem when the enrichR package is loaded.

**Comment by markdane** [comment]
Hi,

This started working yesterday afternoon without any changes on my side. Thank you for your development and support of the package.

Mark Dane

**Comment by markdane** [comment]
Hi,

I have a usage question about enrichR involving differences between scripted and web-accessed Reactome results. Is there a support forum for enrichR or can I get some guidance through email?

Thank you,
Mark Dane

**Comment by wjawaid** [comment]
Hi Mark,

Unfortunately there is no support forum I know of. If you continue to have problems you can report them here or email me directly wajid.jawaid@gmail.com
