### ISSUE TITLE
We moved to https://maayanlab.cloud/Enrichr/

### ISSUE THREAD

**Issue by maxim-k** [wjawaid/enrichR#33]
We recently moved Enrichr to a cloud and changed the URL and setup redirect. So you could just search-replace `https://amp.pharm.mssm.edu/Enrichr` to `https://maayanlab.cloud/Enrichr/`

**Comment by wjawaid** [comment]
Thanks. I'll test and update. Will https://amp.pharm.mssm.edu/Enrichr be decommissioned?

**Comment by maxim-k** [comment]
> Thanks. I'll test and update. Will https://amp.pharm.mssm.edu/Enrichr be decommissioned?

We use redirects now and old URLs are working, but we're not sure we'll keep it this way in the future.
