### ISSUE TITLE
expired: true results with enrichr function

### ISSUE THREAD

**Issue by Youpla705** [wjawaid/enrichR#35]
Hi there, 

I was trying to use the R package this morning and I got the following error when using the enrichr function: 

`expired": true`

I believe this is linked to this old issue: https://github.com/wjawaid/enrichR/issues/13 (server issue ?)

Thanks

**Comment by wjawaid** [comment]
Yes try again. It is likely due to the internet connection or the webserver. If persistent please let me  know again.
