### ISSUE TITLE
p.value and old p.value

### ISSUE THREAD

**Issue by tinggithub33** [wjawaid/enrichR#37]
Thank you for developing this tool!
I am just wondering if the p.value is still calculated using Fisher test, as described in the paper 2013.
your comments will be greatly appreciated.

**Comment by wjawaid** [comment]
Sorry for the delay in response.
It is as you say. The R package is a wrapper to the website. So it is best to check there for the latest in their methods in case they change in the future. The link is https://maayanlab.cloud/Enrichr/help#background
