### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by dm8000** [wjawaid/enrichR#38]
Hello

I see other people also got empty results, but apparently it started working again. I would just like to let you know it is happening to me as well.

I ran this

```
> genes <- c("ADIPOQ", "GHR", "ADIPOR1", "ADIPOR2", "IGFB6", "MTOR")
> enrichment <- enrichr(genes, databases = "KEGG")
Uploading data to Enrichr... Done.
  Querying KEGG... Done.
Parsing results... Done.
```

and "enrichment" was a list with one dataframe (KEGG) with 0 rows and 9 columns. Perhaps I'm doing something wrong?
I checked the same gene list on the website, the outputs came out fine.

**Comment by wjawaid** [comment]
Thanks. I believe this intermittent behaviour was related to the server on which the website was based. Enrichr v3.0 now points to the new server and I hope this resolves the issue.

**Comment by dm8000** [comment]
Hello
I believe this is occurring again, but with WormEnrichr database
