### ISSUE TITLE
enrichR not responding 

### ISSUE THREAD

**Issue by hwessels** [wjawaid/enrichR#39]
Hi, 

I am running enrichR v3 on R version 4.0.0.

Input:
character vector length ~1000

Doing:
enrichR::enrichr(genes = markers.df$gene, databases = "WikiPathways_2019_Human")

Getting:
EnrichR website not responding
NULL

It is the same for any enrichR function
enrichR::listEnrichrDbs()
EnrichR website not responding
NULL

i read this was an issue before in enrichr version 2 and fixed in 2.1.

Any idea why it is reoccurring?

**Comment by ycl6** [comment]
@hwessels When you load the `enrichR` package, did you get a "Connection is Live" message? I have been using it for the past couple of days without issue (using enrichR v3.0). 

Are you able to establish connection since you posted the message?

```R
library(enrichR)
```

```
Welcome to enrichR
Checking connection ... 
Enrichr ... Connection is Live!
FlyEnrichr ... Connection is available!
WormEnrichr ... Connection is available!
YeastEnrichr ... Connection is available!
FishEnrichr ... Connection is available!
```

**Comment by wjawaid** [comment]
@hwessels. There are times the web server may not be responding. If the problem persists it is worth trying on a different machine. Sometimes it can be the way R is installed and it is missing certain libraries so it has problems accessing https:// sites.

@ycl6. Thanks It is working on my machine too.
