### ISSUE TITLE
OxEnrichr as alternative site

### ISSUE THREAD

**Issue by adomingues** [wjawaid/enrichR#41]
Hi @wjawaid,

first of all thank you for developing this package. Makes my life so much easier. Since there is also a corporate site, OxEnrichr, which shares the same base path as all the others, https://maayanlab.cloud/OxEnrichr/, would be possible to add it as option to `enrichR.sites`?

Cheers,
António

**Comment by wjawaid** [comment]
@adomingues Thanks for the suggestion. I'll add that on and will submit to CRAN in the meantime you can use by installing from GitHub.
