### ISSUE TITLE
EnrichR website not responding

### ISSUE THREAD

**Issue by FADHLyemen** [wjawaid/enrichR#42]
```
dbs <- c("GO_Molecular_Function_2015", "GO_Cellular_Component_2015", "GO_Biological_Process_2015")
genes <- c("ADIPOQ", "GHR", "ADIPOR1", "ADIPOR2", "IGFB6", "MTOR")
enrichment <- enrichR::enrichr(genes, databases = "KEGG")
```

**Comment by wjawaid** [comment]
If you want into include KEGG_2021 please include it with the GO databases in `dbs`. Then run `enrichment <- enrichr(genes, databases = dbs)` instead. The given genes don't appear to have any pathway hits within just KEGG_2021.
