### ISSUE TITLE
Next update on CRAN

### ISSUE THREAD

**Issue by ycl6** [wjawaid/enrichR#43]
Hi @wjawaid, I was wondering if you plan to submit a new version to CRAN some time this year? I am hoping to move away from sourcing the required code snippet from another script to use the bugfixed `printEnrich` function to output the enrichR results to files.

**Comment by wjawaid** [comment]
Hi

Yes planning to submit in December.

**Comment by ycl6** [comment]
Hi @wjawaid, thanks for the update!
