### ISSUE TITLE
Is it possible to use gsea with this?

### ISSUE THREAD

**Issue by smk5g5** [wjawaid/enrichR#45]
Hi,

I was wondering if it is possible to do gene set enrichment analysis with this package? It is my understanding that it is only doing over-representation analysis right now is that correct? Kindly let me know. Thanks!

**Comment by ycl6** [comment]
Hi @smk5g5 The short answer is no. The `enrichR` R package is an interface that submit the query to the [Enrichr](https://maayanlab.cloud/Enrichr/) web server to run the analysis. The package itself does not perform any analysis. You can try [clusterProfiler](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) if you are looking for a R package that performs GESA and/or ORA.
