### ISSUE TITLE
It is possible to implement a function to define background genes?

### ISSUE THREAD

**Issue by ulianaf** [wjawaid/enrichR#47]
Hi,
 I was wondering if it is possible to set background genes to calculate the enrichment
Thanks for your work!

**Comment by sparsepix** [comment]
The option is apparently included in the API now, but still not visible on the Web version as well :(

**Comment by wjawaid** [comment]
[Enrichr](https://maayanlab.cloud/Enrichr/) precomputes a background gene set and does not as far as I know allow you to provide a background. See [here](https://maayanlab.cloud/Enrichr/help#background&q=4) for more info.

**Comment by ChBustam** [comment]
Adding your background genes is an option already available on the web version. It would be great to have that option here.

**Comment by wjawaid** [comment]
Hi,

Thanks for letting me know. I’ll look into it and try and introduce it as a new feature for the next update.

Best wishes,
Wajid
