### ISSUE TITLE
EnrichR website not responding

### ISSUE THREAD

**Issue by alex-meta** [wjawaid/enrichR#50]
When i Install enrichR_3.0 from CRAN - package not works:

> library("enrichR")
Welcome to enrichR
Checking connection ... 
EnrichR website not responding
Enrichr ... EnrichR website not responding
FlyEnrichr ... EnrichR website not responding
WormEnrichr ... EnrichR website not responding
YeastEnrichr ... EnrichR website not responding
FishEnrichr ... 

Also i tried to install package from github, same errors are displayed.

**Comment by dottercp** [comment]
Hi,

I ran into the same issue, more specifically, when trying:
`httr::GET("https://maayanlab.cloud")`
I got: 
`Error in curl::curl_fetch_memory(url, handle = handle) : schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326)`

After looking into it the solution I found was to put
`CURL_SSL_BACKEND=openssl` 
in my .Renviron file (as per the suggestion [here](https://stackoverflow.com/a/64373553)).

Hope this helps.

**Comment by wjawaid** [comment]
Hi,

Thanks. That’s very helpful.
