### ISSUE TITLE
Erroneous gene ratios when pathways have similar names

### ISSUE THREAD

**Issue by longjp** [wjawaid/enrichR#54]
plotEnrich produces a bar for each unique pathway name after truncating pathway name to numChar. However since several pathways have similar names (same leading 40 characters), this can result in the bars of different pathways being added together (ggplot2 default). In an application I am working on, I had a Gene Ratio of over 1 on the plot, which is impossible. Below is a MWE with fake data. I believe enforcing unique truncated pathway names would fix the issue:

```
library(enrichR)
df <- data.frame(Term=c("Pathway 1 with similar name",
                        "Pathway 1 with similar name but slighly different",
                        "Pathway 3",
                        "Pathway 4"),
                 Overlap=c("10/15","15/20","1/10","3/30"),
                 P.value=c(0.0001,0.0002,0.3,0.5))

# works because all pathways have unique names when truncated to 40 characters
plotEnrich(df,showTerms=3,
           numChar = 40,y="Ratio",
           orderBy="P.value",
           title="Title")

# fails because bars from two pathways with similar names are merged together
plotEnrich(df,showTerms=3,
           numChar = 20,y="Ratio",
           orderBy="P.value",
           title="Title")
```

On a project with real data I got this:

![Screen Shot 2022-09-21 at 11 32 31 AM](https://user-images.githubusercontent.com/462271/191564511-d135eae7-c368-47a2-a54b-6955c9b29861.png)

**Comment by ycl6** [comment]
Hi @longjp Thanks for reporting this bug, I have submitted a PR which should fix this.

**Comment by wjawaid** [comment]
Thanks ycl6. I've accepted you pull request. Just waiting for CRAN to accept.
