### ISSUE TITLE
offline   enrichR

### ISSUE THREAD

**Issue by saeidamiri1** [wjawaid/enrichR#56]
We want to use enrichR using HPC, when we submit the job, it can not connect to the internet, how can we use enrichR offline?

> library(enrichR)
Welcome to enrichR
Checking connection ...
Error: package or namespace load failed for ‘enrichR’:
 .onAttach failed in attachNamespace() for 'enrichR', details:
  call: curl::curl_fetch_memory(url, handle = handle)
  error: Failed to connect to maayanlab.cloud port 443 after 40 ms: Connection refused

**Comment by ycl6** [comment]
Hi @saeidamiri1 The `enrichR` R package is an interface that connects and uses the resources provided by the [Enrichr](https://maayanlab.cloud/Enrichr/) tool. I wasn't aware an offline database is available but you can make enquiries with the [Ma'ayan Lab](https://labs.icahn.mssm.edu/maayanlab/)
