### ISSUE TITLE
offline genesets

### ISSUE THREAD

**Issue by jjacob12** [wjawaid/enrichR#59]
Hi,
Thanks so much for this powerful tool. I used a recently developed [Seurat command](https://satijalab.org/seurat/reference/deenrichrplot) to test for gene set enrichment which works very well, but requires an internet connection. This is not straightforward when using e.g. RStudio server on a HPC server. It would be really great to be able to use this seurat command without needing an internet connection. Is this something you could look at?  I am not sure whether this should be addressed by you or by the Seurat developers so I will raise the same issue on the Seurat GitHub.

**Comment by ycl6** [comment]
Hi @jjacob12 The `enrichR` R package is an interface that connects and uses the resources provided by the [Enrichr](https://maayanlab.cloud/Enrichr/) tool. Hence, you'll need to speak with [Enrichr](https://maayanlab.cloud/Enrichr/) to see if they can release a database or software for offline queries. At present, queries are submmited to the website for analysis.

**Comment by wjawaid** [comment]
Hi @jjacob12. I don't have offline access to the data. enrichR gets data from the [Enrichr](https://maayanlab.cloud/Enrichr/) website. It's not something I can change. I don't know if there is a way you can tunnnel a internet link via the computer you use to access the HPC.

**Comment by jjacob12** [comment]
Thanks for looking into this. I will try and find a workaround. Perhaps you could consider this for a future iteration of EnrichR which is such a great tool and works superbly with Seurat? I also found it much easier to use than some of the other well known software tools for this task.
