### ISSUE TITLE
input genelists

### ISSUE THREAD

**Issue by pbrazda** [wjawaid/enrichR#6]
Hi, 

I have two basic questions on enrichR:

1) How could I input genelists (instead of manually listing genes) into enrichr?
at:
`enriched <- enrichr(c("Runx1", "Gfi1", "Gfi1b", "Spi1", "Gata1", "Kdr"), dbs)`

2) Is it possible to input multiple genelists and receive a table with multiple "Term" maybe?

Thank you for your response!

Best, 
Peter

**Comment by wjawaid** [comment]
Hi Peter,

The package will not do this by itself but you could try to use R's `lapply()` function to send multiple lists and return the result in a superlist.

Wajid
