### ISSUE TITLE
Extract gene sets from databases instead of providing list of genes

### ISSUE THREAD

**Issue by JuanFLB** [wjawaid/enrichR#60]
Hello!

Awesome work, kudos for the little package. It is awesome to streamline work in R when exploring your genes of interest. Many thanks.

My inquiry comes for it could be possible to get the gene sets from the different datasets, instead of providing a list of genes?
Since we are able to connect to the Enricher database, and from the short knowledge I have, when pulling the databases, it should also be possible to extract from them the different sets that are used as reference for the usual Enrichr analysis.

Thanks for your work and your time.

**Comment by wjawaid** [comment]
I'm not sure. You could try and send large lists to probe the dataset. The returned report does tell you how big the gene set is, how many overlaps you have and which genes overlap. I don't think it provides the list of genes in the set that your gene list hasn't hit so it may be rather difficult.
