### ISSUE TITLE
ImmuneSigDB

### ISSUE THREAD

**Issue by jamesdahlvang** [wjawaid/enrichR#62]
Hi,

Thank you for this tool. It has proved immensely useful thus far. I'm excited to keep exploring my data with it!

It would be nice if the immune signatures from the MSigDB were added to the library. Do you envision this happening anytime soon? Thanks again

**Comment by wjawaid** [comment]
Hi @jamesdahlvang. This tool only provides an interface to [Enrichr](https://maayanlab.cloud/Enrichr/). I think Bioconductor already has a [msigdb](https://bioconductor.org/packages/release/data/experiment/html/msigdb.html) package.
