### ISSUE TITLE
"line 7 did not have 2 elements" error when passing a long gene list

### ISSUE THREAD

**Issue by atakanekiz** [wjawaid/enrichR#7]
Hi,

Thanks for this very helpful package. I'm running into a problem, and I can't seem to find a way around it.

I'm analyzing single-cell RNA seq data. First, I subsetted the cells of interest from the main expression matrix and calculated a ranked gene list by using S2N metric between different conditions. I'm not doing a differential expression analysis to filter the genes, rather I'm generating the ranked list from by using all the genes. I have around ~11,000 genes in my ranked list. When I pass the whole list I get the following error:

```
> enrichr_test <- as.data.frame(enrichr(genes = names(cd3cd8_wt_D12vsD9_rnk), databases = "GO_Biological_Process_2017b" ))
Uploading data to Enrichr... Done.
  Querying GO_Biological_Process_2017b... Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 7 did not have 2 elements
```

When I trim the gene list down by selecting the first `8400` genes or so this error goes away and I can see the results of enrichment analysis. I tried few other numbers and seems like it fails somewhere around `8450` genes. Selecting different `database` arguments did not have any effect on the error. 

I searched online about the error and I don't fully understand what it means in this context. Any insights are appreciated.

Thanks
Atakan

**Comment by wjawaid** [comment]
Can i download the list of genes from somewhere? It seems that the data returned by Enrichr is in a different format for a particular enrichment term.

**Comment by kliolak** [comment]
Hi, any updated on this?
I have the same issue. I attach the gene list. 
Many thanks,
Klio
[pathsEnrichr.txt](https://github.com/wjawaid/enrichR/files/2410252/pathsEnrichr.txt)

**Comment by AdrianS85** [comment]
> Hi, any updated on this?
> I have the same issue. I attach the gene list.
> Many thanks,
> Klio
> [pathsEnrichr.txt](https://github.com/wjawaid/enrichR/files/2410252/pathsEnrichr.txt)

Hey kliolak. Just in case this issue is still relevant to You - I think its caused by long gene lists (also see: https://www.biostars.org/p/349240/#350866). I dont have any solution, unfortunalty...
