### ISSUE TITLE
empty lists

### ISSUE THREAD

**Issue by rb643** [wjawaid/enrichR#8]
HI Wajid,

Thanks for maintaining this wonderful interface to EnrichR. I've noticed that when I upload empty gene-lists I also get a results table with hits.. Any thoughts on why this might be the case? Nothing passes fdr of course, but its still a bit odd maybe?

Cheers,

Richard

**Comment by wjawaid** [comment]
Hi Richard,

Sorry for the delay in responding but that is interesting. The package is just a wrapper for the EnrichR website and simply uploads the gene list and parses the data. I should have include a check for an empty listy. It is probably returning some sort of  prior probability that the EnrihcR website uses. But I am not sure.

Wajid
