### ISSUE TITLE
How did you compute Adjusted.P.value?

### ISSUE THREAD

**Issue by xsun1229** [wjawaid/enrichR#85]
Hi Wajid, 

I noticed that the EnrichR results include an Adjusted.P.value column. Could you clarify how this value was computed? The Adjusted.P.values seem consistently smaller than expected, so I was wondering if any filtering was applied to the gene sets before correcting the original Fisher's exact test p-values.

Thanks!
Xiaotong

**Comment by ycl6** [comment]
Hi @xsun1229 

As in my reply to your other questions (https://github.com/wjawaid/enrichR/issues/72#issuecomment-2481317224), you'll have to reach out to the [Enrichr developers](https://github.com/MaayanLab/enrichr_issues) about the analysis itself.
